# Generated by Django 5.0 on 2024-01-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesection',
            name='questionnaire_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='responsesection',
            name='questionnaire_section_id',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
