# Generated by Django 5.0 on 2024-01-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_responsesection_questionnaire_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSharingTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tagged_profile_id', models.CharField(max_length=100)),
                ('article_id', models.CharField(max_length=100)),
                ('tagged_profile_endorsed', models.BooleanField(default=False)),
                ('endorsed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
